-- MySQL Script generated by MySQL Workbench
-- 03/19/17 23:03:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdmunicipiocuenavaca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdmunicipiocuenavaca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdmunicipiocuenavaca` DEFAULT CHARACTER SET latin1 ;
USE `bdmunicipiocuenavaca` ;

-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbl_log_reg_areaspago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbl_log_reg_areaspago` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbl_log_reg_areaspago` (
  `idtbl_log_reg_areaspago` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `log_tramite` INT(11) NOT NULL COMMENT '',
  `clave` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `timestamp` TIMESTAMP NOT NULL COMMENT '',
  `usuario` INT(11) NOT NULL COMMENT '',
  `actividad` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idtbl_log_reg_areaspago`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `log_tramite` ON `bdmunicipiocuenavaca`.`tbl_log_reg_areaspago` (`log_tramite` ASC, `clave` ASC, `usuario` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbl_log_reg_requisito_por_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbl_log_reg_requisito_por_tramite` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbl_log_reg_requisito_por_tramite` (
  `idtbl_log_reg_requisito_por_tramite` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_log_tramites` INT(11) NOT NULL COMMENT '',
  `clave` INT(11) NOT NULL COMMENT '',
  `posicion` INT(11) NOT NULL COMMENT '',
  `vineta` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `archivo` TEXT NOT NULL COMMENT '',
  `tipo` VARCHAR(50) NOT NULL COMMENT '',
  `copias_originales` VARCHAR(50) NOT NULL COMMENT '',
  `cantidad_copias` VARCHAR(50) NOT NULL COMMENT '',
  `timestamp` TIMESTAMP NOT NULL COMMENT '',
  `usuario` VARCHAR(50) NOT NULL COMMENT '',
  `actividad` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idtbl_log_reg_requisito_por_tramite`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `id_log_tramites` ON `bdmunicipiocuenavaca`.`tbl_log_reg_requisito_por_tramite` (`id_log_tramites` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbl_log_reg_tramites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbl_log_reg_tramites` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbl_log_reg_tramites` (
  `idtbl_log_reg_tramites` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `log_tramite` INT(11) NOT NULL COMMENT '',
  `clave` VARCHAR(100) NOT NULL COMMENT '',
  `dependencia` VARCHAR(200) NOT NULL COMMENT '',
  `unidad_adminitrativa` DATE NOT NULL COMMENT '',
  `otras_oficinas` TEXT NOT NULL COMMENT '',
  `tema` VARCHAR(50) NOT NULL COMMENT '',
  `perfil` VARCHAR(50) NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `tipo` VARCHAR(50) NOT NULL COMMENT '',
  `caso_tramite` TEXT NOT NULL COMMENT '',
  `medio_presentacion` TEXT NOT NULL COMMENT '',
  `medio_presentacion_archivo` TEXT NOT NULL COMMENT '',
  `horario_atencion` VARCHAR(50) NOT NULL COMMENT '',
  `plazo_resolucion_texto` TEXT NOT NULL COMMENT '',
  `vigencia` VARCHAR(50) NOT NULL COMMENT '',
  `aplicacion_silencio` VARCHAR(50) NOT NULL COMMENT '',
  `obervaciones` TEXT NOT NULL COMMENT '',
  `costo_texto` TEXT NOT NULL COMMENT '',
  `costo_archivo` VARCHAR(50) NOT NULL COMMENT '',
  `criterios_resolucion` TEXT NOT NULL COMMENT '',
  `fundamentos_juridicos` TEXT NOT NULL COMMENT '',
  `quejas` VARCHAR(50) NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  `timestamp` TIMESTAMP NOT NULL COMMENT '',
  `usuario` VARCHAR(50) NOT NULL COMMENT '',
  `actividad` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idtbl_log_reg_tramites`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `log_tramite` ON `bdmunicipiocuenavaca`.`tbl_log_reg_tramites` (`log_tramite` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbl_log_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbl_log_usuarios` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbl_log_usuarios` (
  `idtbl_log_usuarios` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idusuario` INT(11) NULL DEFAULT NULL COMMENT '',
  `ip` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `fecha_registro` DATETIME NOT NULL COMMENT '',
  `actividad` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idtbl_log_usuarios`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `idusuario_UNIQUE` ON `bdmunicipiocuenavaca`.`tbl_log_usuarios` (`idusuario` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbl_log_vistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbl_log_vistas` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbl_log_vistas` (
  `idtbl_log_vistas` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `clave_tramite` INT(11) NOT NULL COMMENT '',
  `dependencia` INT(11) NOT NULL COMMENT '',
  `timestamp` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`idtbl_log_vistas`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `clave_tramite` ON `bdmunicipiocuenavaca`.`tbl_log_vistas` (`clave_tramite` ASC, `dependencia` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbl_log_vistas_bkp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbl_log_vistas_bkp` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbl_log_vistas_bkp` (
  `idtbl_log_vistas_bkp` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `clave_tramite` INT(11) NOT NULL COMMENT '',
  `timestamp` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idtbl_log_vistas_bkp`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `clave_tramite` ON `bdmunicipiocuenavaca`.`tbl_log_vistas_bkp` (`clave_tramite` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tblareaspago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tblareaspago` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tblareaspago` (
  `idtblAreasPago` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `clavetramite` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `nombre` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `tipo` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `fecharegistro` DATE NOT NULL COMMENT '',
  `usuarioregistro` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `status` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idtblAreasPago`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tblgobiernos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tblgobiernos` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tblgobiernos` (
  `idtblGobiernos` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `logo` VARCHAR(50) NOT NULL COMMENT '',
  `usuario_registro` VARCHAR(200) NOT NULL COMMENT '',
  `fecha_registro` DATE NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idtblGobiernos`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idtblGobiernos` ON `bdmunicipiocuenavaca`.`tblgobiernos` (`idtblGobiernos` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tblrequisitostramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tblrequisitostramite` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tblrequisitostramite` (
  `idtblrequisitostramite` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `clavetramite` VARCHAR(45) NOT NULL COMMENT '',
  `posicion` INT(11) NOT NULL COMMENT '',
  `vineta` VARCHAR(10) NOT NULL COMMENT '',
  `nombre` TEXT NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `archivo` VARCHAR(500) NOT NULL COMMENT '',
  `tipo` VARCHAR(50) NOT NULL COMMENT '',
  `copiasoriginales` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `catidadcopias` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `fecharegistro` DATE NOT NULL COMMENT '',
  `usuarioregistro` VARCHAR(50) NOT NULL COMMENT '',
  `status` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idtblrequisitostramite`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tblperfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tblperfil` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tblperfil` (
  `idtblPerfil` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idtblPerfil`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idtblPerfil` ON `bdmunicipiocuenavaca`.`tblperfil` (`idtblPerfil` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbltemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbltemas` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbltemas` (
  `idtblTemas` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idtblTemas`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idtblTemas` ON `bdmunicipiocuenavaca`.`tbltemas` (`idtblTemas` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbltramites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbltramites` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbltramites` (
  `idtbltramite` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `clave` VARCHAR(50) NOT NULL COMMENT '',
  `idtbldependencia` INT(11) NOT NULL COMMENT '',
  `unidadadministrativa` TEXT NOT NULL COMMENT '',
  `otrasofiinas` TEXT NOT NULL COMMENT '',
  `idtbltemas` INT(11) NULL DEFAULT NULL COMMENT '',
  `idtblperfil` INT(11) NOT NULL COMMENT '',
  `nombre` TEXT NULL DEFAULT NULL COMMENT '',
  `tipo` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `casostramite` TEXT NULL DEFAULT NULL COMMENT '',
  `mediopresentacion` TEXT NULL DEFAULT NULL COMMENT '',
  `mediopresentacionarchivo` VARCHAR(500) NOT NULL COMMENT '',
  `horarioatencion` TEXT NOT NULL COMMENT '',
  `plazoresolucion` TEXT NULL DEFAULT NULL COMMENT '',
  `vigencia` VARCHAR(500) NULL DEFAULT NULL COMMENT '',
  `aplicacionsilencia` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `observaciones` TEXT NULL DEFAULT NULL COMMENT '',
  `costotexto` TEXT NULL DEFAULT NULL COMMENT '',
  `costoarchivo` VARCHAR(500) NOT NULL COMMENT '',
  `criteriosresolucion` TEXT NULL DEFAULT NULL COMMENT '',
  `fundamentosjuridicos` TEXT NULL DEFAULT NULL COMMENT '',
  `quejas` TEXT NULL DEFAULT NULL COMMENT '',
  `fechasregistro` DATE NULL DEFAULT NULL COMMENT '',
  `usuarioregistro` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `fechaupdate` TIMESTAMP NOT NULL COMMENT '',
  `usuarioupdate` VARCHAR(50) NOT NULL COMMENT '',
  `status` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `contador` INT(11) NOT NULL COMMENT '',
  `tblrequisitostramite_idtblrequisitostramite` INT(11) NOT NULL COMMENT '',
  `tblperfil_idtblPerfil` INT(11) NOT NULL COMMENT '',
  `tbltemas_idtblTemas` INT(11) NOT NULL COMMENT '',
  `tblareaspago_idtblAreasPago` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idtbltramite`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idtbltemas` ON `bdmunicipiocuenavaca`.`tbltramites` (`idtbltemas` ASC, `idtblperfil` ASC)  COMMENT '';

CREATE UNIQUE INDEX `tblrequisitostramite_idtblrequisitostramite_UNIQUE` ON `bdmunicipiocuenavaca`.`tbltramites` (`tblrequisitostramite_idtblrequisitostramite` ASC)  COMMENT '';

CREATE UNIQUE INDEX `tblperfil_idtblPerfil_UNIQUE` ON `bdmunicipiocuenavaca`.`tbltramites` (`tblperfil_idtblPerfil` ASC)  COMMENT '';

CREATE UNIQUE INDEX `tbltemas_idtblTemas_UNIQUE` ON `bdmunicipiocuenavaca`.`tbltramites` (`tbltemas_idtblTemas` ASC)  COMMENT '';

CREATE UNIQUE INDEX `tblareaspago_idtblAreasPago_UNIQUE` ON `bdmunicipiocuenavaca`.`tbltramites` (`tblareaspago_idtblAreasPago` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tbldependencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tbldependencias` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tbldependencias` (
  `idtblDependencias` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idtblGobierno` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(500) NOT NULL COMMENT '',
  `calle` VARCHAR(500) NOT NULL COMMENT '',
  `numExt` VARCHAR(10) NOT NULL COMMENT '',
  `numInt` VARCHAR(10) NOT NULL COMMENT '',
  `colonia` VARCHAR(50) NOT NULL COMMENT '',
  `idtblMunicipios` INT(11) NOT NULL COMMENT '',
  `telefono` VARCHAR(50) NOT NULL COMMENT '',
  `email` VARCHAR(50) NOT NULL COMMENT '',
  `web` VARCHAR(200) NOT NULL COMMENT '',
  `horario` VARCHAR(50) NOT NULL COMMENT '',
  `url` VARCHAR(500) NOT NULL COMMENT '',
  `lat` VARCHAR(100) NOT NULL COMMENT '',
  `ing` VARCHAR(100) NOT NULL COMMENT '',
  `fecha_registro` DATE NOT NULL COMMENT '',
  `usuario_registro` VARCHAR(50) NOT NULL COMMENT '',
  `fecha_update` TIMESTAMP NOT NULL COMMENT '',
  `usuario_update` VARCHAR(50) NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  `tbltramites_idtbltramite` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idtblDependencias`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idtblGobierno` ON `bdmunicipiocuenavaca`.`tbldependencias` (`idtblGobierno` ASC)  COMMENT '';

CREATE INDEX `idtblGobierno_2` ON `bdmunicipiocuenavaca`.`tbldependencias` (`idtblGobierno` ASC)  COMMENT '';

CREATE UNIQUE INDEX `tbltramites_idtbltramite_UNIQUE` ON `bdmunicipiocuenavaca`.`tbldependencias` (`tbltramites_idtbltramite` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tblmunicipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tblmunicipios` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tblmunicipios` (
  `idtblMunicipios` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `tbldependencias_idtblDependencias` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idtblMunicipios`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idtblMunicipios` ON `bdmunicipiocuenavaca`.`tblmunicipios` (`idtblMunicipios` ASC)  COMMENT '';

CREATE UNIQUE INDEX `tbldependencias_idtblDependencias_UNIQUE` ON `bdmunicipiocuenavaca`.`tblmunicipios` (`tbldependencias_idtblDependencias` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tblusuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tblusuarios` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tblusuarios` (
  `idtblUsuarios` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idtblGobiernos` INT(11) NOT NULL COMMENT '',
  `password` VARCHAR(50) NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `apaterno` VARCHAR(50) NOT NULL COMMENT '',
  `amaterno` VARCHAR(50) NOT NULL COMMENT '',
  `perfil` VARCHAR(20) NOT NULL COMMENT '',
  `cargo` VARCHAR(50) NOT NULL COMMENT '',
  `email` VARCHAR(50) NOT NULL COMMENT '',
  `telefono` VARCHAR(50) NOT NULL COMMENT '',
  `fecha_registro` DATE NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  `tbltramites_idtbltramite` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idtblUsuarios`, `tbltramites_idtbltramite`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idtblUsuarios` ON `bdmunicipiocuenavaca`.`tblusuarios` (`idtblUsuarios` ASC)  COMMENT '';

CREATE INDEX `idtblGobierno` ON `bdmunicipiocuenavaca`.`tblusuarios` (`idtblGobiernos` ASC)  COMMENT '';

CREATE INDEX `idtblGobiernos` ON `bdmunicipiocuenavaca`.`tblusuarios` (`idtblGobiernos` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `bdmunicipiocuenavaca`.`tlb_log_tramites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdmunicipiocuenavaca`.`tlb_log_tramites` ;

CREATE TABLE IF NOT EXISTS `bdmunicipiocuenavaca`.`tlb_log_tramites` (
  `idtbl_log_tramites` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idusuario` INT(11) NOT NULL COMMENT '',
  `ip` VARCHAR(50) NOT NULL COMMENT '',
  `fecha_registro` TIMESTAMP NOT NULL COMMENT '',
  `actividad` VARCHAR(50) NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `idtramite` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idtbl_log_tramites`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `idusuario` ON `bdmunicipiocuenavaca`.`tlb_log_tramites` (`idusuario` ASC, `idtramite` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
